# Generated by Django 3.2.19 on 2023-06-09 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('breakfasts', models.ManyToManyField(related_name='breafasts', to='view_menu.FoodMenu')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('dinners', models.ManyToManyField(related_name='dinners', to='view_menu.FoodMenu')),
                ('drinks', models.ManyToManyField(related_name='drinks', to='view_menu.FoodMenu')),
                ('lunchs', models.ManyToManyField(related_name='lunchs', to='view_menu.FoodMenu')),
                ('sides', models.ManyToManyField(related_name='sides', to='view_menu.FoodMenu')),
            ],
        ),
    ]
