# Generated by Django 3.2.19 on 2023-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0002_auto_20230615_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuPrice',
            new_name='BreakFast',
        ),
    ]
