# Generated by Django 3.2.19 on 2023-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodtype/'),
        ),
    ]
