# Generated by Django 3.2.19 on 2023-06-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0003_alter_foodmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
