# Generated by Django 3.2.19 on 2023-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0003_rename_menuprice_breakfast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fimage', models.ImageField(upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fimage', models.ImageField(upload_to='menu_images')),
            ],
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fimage', models.ImageField(upload_to='menu_images')),
            ],
        ),
    ]
