# Generated by Django 3.2.19 on 2023-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0007_alter_breakfast_fimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='fimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='fimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sides',
            name='fimage',
            field=models.URLField(),
        ),
    ]
