# Generated by Django 3.2.19 on 2023-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0008_auto_20230616_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='dinner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lunch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sides',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='breakfast',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
