# Generated by Django 3.2.19 on 2023-07-15 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view_menu', '0010_auto_20230620_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='sides',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sides',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
    ]
