# Generated by Django 3.2.19 on 2023-06-22 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_managebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='createtable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Table'),
        ),
        migrations.AddField(
            model_name='managebooking',
            name='createtable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.Table'),
        ),
        migrations.AddField(
            model_name='managebooking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
