# Generated by Django 3.2.19 on 2023-06-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=20)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (8, '8'), (14, '14'), (20, '20')], default=2)),
                ('table_position', models.CharField(choices=[('window', 'Tables near the window'), ('middle', 'Tables in the middle'), ('outside', 'Tables outside in the garden'), ('corridor', 'Tables on the corridor')], default='window', max_length=10)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
    ]
