# Generated by Django 3.2.19 on 2023-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.CharField(choices=[('2_persons', '2_persons'), ('3_persons', '3_persons'), ('4_persons', '4_persons'), ('8_persons', '8_persons'), ('14_persons', '14_persons'), ('18_persons', '18_persons'), ('20_persons', '20_persons'), ('25_persons', '25_persons'), ('30_persons', '30_persons')], default='2_persons', max_length=11)),
                ('table_position', models.CharField(choices=[(' table by window', 'Tables by window'), (' table in middle', 'Tables in middle'), (' table in garden', 'Tables in the garden'), (' table in corridor', 'Tables on the corridor')], default='Tables by window', max_length=25)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
