# Generated by Django 3.2.19 on 2023-06-21 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (8, '8'), (14, '14')], default=2)),
                ('table_position', models.CharField(choices=[('window', 'Tables near the window'), ('middle', 'Tables in the middle'), ('outside', 'Tables outside in the garden'), ('corridor', 'Tables on the corridor')], default='window', max_length=10)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('reservation_date_and_time', models.DateTimeField(null=True)),
                ('number_of_guests', models.IntegerField(default=2)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.IntegerField(choices=[(1, '8:00am - 9:45am'), (2, '10:00am - 12:45pm'), (3, '1:00pm - 2:45pm'), (4, '3:00pm - 5:45pm'), (5, '7:00pm - 8:45pm')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_table', to='booking.createtable')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
