# Generated by Django 3.2.19 on 2023-06-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('avaliable', 'Available'), ('not_avaliable', 'Not Available')], default='avaliable', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('2', '2_persons'), ('2', '3_persons'), ('4', '4_persons'), ('8', '8_persons'), ('14', '14_persons'), ('20', '20_persons')], default='2_persons', max_length=11),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(choices=[('table 2', '2'), ('table 3', '3'), ('table 4', '4'), ('tabele 8', '8'), ('table 14', '14'), ('table 20', '20')], default='2', max_length=18),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_position',
            field=models.CharField(choices=[(' is table by window', 'Tables by window'), (' is in middle', 'Tables in middle'), (' table in garden', 'Tables in the garden'), (' table in corridor', 'Tables on the corridor')], default='Tables by window', max_length=25),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.CharField(choices=[('8:00am - 9:45am', '8:00am - 9:45am'), ('10:00am - 12:45pm', '10:00am - 12:45pm'), ('1:00pm - 2:45pm', '1:00pm - 2:45pm'), ('3:00pm - 5:45pm', '3:00pm - 5:45pm'), ('7:00pm - 8:45pm', '7:00pm - 8:45pm')], default='8:00am - 9:45am', max_length=20)),
                ('customer', models.ForeignKey(default='Customer', on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('table', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
    ]
