# Generated by Django 3.2.19 on 2023-06-25 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=2)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.IntegerField(choices=[(1, '8:00am - 9:45am'), (2, '10:00am - 12:45pm'), (3, '1:00pm - 2:45pm'), (4, '3:00pm - 5:45pm'), (5, '7:00pm - 8:45pm')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer_name', 'reservation_time', 'reservation_date'],
            },
        ),
    ]
