# Generated by Django 3.2.19 on 2023-06-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20230630_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('2_person', '2_persons'), ('2_person', '3_persons'), ('4_person', '4_persons'), ('8_person', '8_persons'), ('14_person', '14_persons'), ('16_person', '16_persons'), ('20_person', '20_persons'), ('24_person', '24_persons'), ('30_person', '30_persons'), ('35_person', '35_persons')], default='2_persons', max_length=11),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
