# Generated by Django 3.2.19 on 2023-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_num',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (8, '8'), (14, '14'), (20, '20')], null=True),
        ),
    ]
