# Generated by Django 3.2.19 on 2023-06-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
    ]
