# Generated by Django 3.2.19 on 2023-06-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking_numbers', to='booking.table'),
        ),
    ]
