# Generated by Django 3.2.19 on 2023-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20230628_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('table 2', '2'), ('table 3', '3'), ('table 4', '4'), ('tabele 8', '8'), ('table 14', '14'), ('table 20', '20')], default='2', max_length=18),
        ),
    ]
