# Generated by Django 3.2.19 on 2023-06-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_table_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='category',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
