# Generated by Django 3.2.19 on 2023-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20230628_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_position',
            field=models.CharField(choices=[(' is table by window', 'Tables by window'), (' is in middle', 'Tables in middle'), (' table in garden', 'Tables in the garden'), (' table in corridor', 'Tables on the corridor')], default='Tables by window', max_length=25),
        ),
    ]
