# Generated by Django 3.2.19 on 2023-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('2_person', '2_persons'), ('4_person', '4_persons'), ('8_person', '8_persons'), ('16_person', '16_persons'), ('24_person', '24_persons'), ('35_person', '35_persons')], default='2_persons', max_length=11),
        ),
    ]
