# Generated by Django 3.2.19 on 2023-07-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fimage', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SIDE', 'Side')], default='breakfast', max_length=25)),
                ('description', models.TextField(default='food_description')),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegetarian', models.BooleanField(default=False)),
                ('calorie_count', models.IntegerField(default=0)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by_staff', models.CharField(default='staff', max_length=25)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('breakfasts', models.ManyToManyField(related_name='breakfasts', to='food.MenuItem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('dinners', models.ManyToManyField(related_name='dinners', to='food.MenuItem')),
                ('lunchs', models.ManyToManyField(related_name='lunchs', to='food.MenuItem')),
                ('sides', models.ManyToManyField(related_name='sides', to='food.MenuItem')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
